### ISSUE TITLE
Timeout Error trying to get  data: { timeout: 5000, method: 'find', path: 'portfolios' }

### ISSUE THREAD

**Issue by MrGRA** [Mattchewone/crypto-dashboard#1]
Hi Matt,

I get the following error:

```
  nuxt:render Rendering url / +3m
{ Timeout: Timeout of 5000ms exceeded calling find on portfolios
    at new Timeout (/Users/guilhermealmeida/Sites/abis/abis-docker-aws/app/ui/node_modules/@feathersjs/errors/lib/index.js:135:17)
    at Timeout.setTimeout [as _onTimeout] (/Users/guilhermealmeida/Sites/abis/abis-docker-aws/app/ui/node_modules/@feathersjs/transport-commons/lib/client.js:66:9)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
  type: 'FeathersError',
  name: 'Timeout',
  message: 'Timeout of 5000ms exceeded calling find on portfolios',
  code: 408,
  className: 'timeout',
  data: { timeout: 5000, method: 'find', path: 'portfolios' },
  errors: {},
  statusCode: 500 }

 ERROR

  Timeout: Timeout of 5000ms exceeded calling find on portfolios

  - index.js:135 new Timeout
    [ui]/[@feathersjs]/errors/lib/index.js:135:17

  - client.js:66 Timeout.setTimeout [as _onTimeout]
    [ui]/[@feathersjs]/transport-commons/lib/client.js:66:9

  - timers.js:466 ontimeout
    timers.js:466:11

  - timers.js:304 tryOnTimeout
    timers.js:304:5

  - timers.js:267 Timer.listOnTimeout
    timers.js:267:5
```
Am I missing something in the store/index.js

Thanks

**Comment by MrGRA** [comment]
Forget it,
It was a misconfiguration on the API.

Everything is fine now!
